### ISSUE TITLE
Error running #python3 main.py

### ISSUE THREAD

**Issue by C-Fu** [sem/NFT-Image-Generator#2]
``` ~/NFT-Image-Generator# python3 main.py
Traceback (most recent call last):
  File "main.py", line 428, in <module>
    main()
  File "main.py", line 415, in main
    m.setup()
  File "main.py", line 168, in setup
    custom_rarity_rage = self.config.get('rarity')
  File "main.py", line 38, in get
    self.data = json.load(conf)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 23 column 33 (char 1342)
```

What's the issue?
Folder structure is simple as well
![image](https://user-images.githubusercontent.com/6426597/157330345-e43e0b7d-fa6c-4960-8a53-ea8dd5f9c6fb.png)

**Comment by mahmoudabdelnasser5524** [comment]
I also have the same problem.

Traceback (most recent call last):
  File "C:\Users\cf\NFT-Image-Generator\main.py", line 428, in <module>
    main()
  File "C:\Users\cf\NFT-Image-Generator\main.py", line 415, in main
    m.setup()
  File "C:\Users\cf\NFT-Image-Generator\main.py", line 168, in setup
    custom_rarity_rage = self.config.get('rarity')
  File "C:\Users\cf\NFT-Image-Generator\main.py", line 38, in get
    self.data = json.load(conf)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 25 column 33 (char 987)

**Comment by mahmoudabdelnasser5524** [comment]
Did you know how to solve the problem?

**Comment by ctrl-Felix** [comment]
There is a bug in the config.json. Change the config to:
```
"rarity": {
        "3 eyes/normal_eyes.png": 10.0,
        "2 body/male.png": 0.5,
        "1 background/red.png": 140.0
    }
```
